### ISSUE TITLE
2.0.6: missing install time `tomli_w` dependency?🤔 

### ISSUE THREAD

**Issue by kloczek** [pdm-project/pdm-backend#169]
Just have been trying to update `atpublic` (https://gitlab.com/warsaw/public) to use `pdm-backend` instead `pdm-pep517` and I found that pep517 build fails because  `pdm-backend` needs`tomli_w`
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/pdm/backend/__init__.py", line 20, in get_requires_for_build_wheel
    from pdm.backend.wheel import WheelBuilder
  File "/usr/lib/python3.8/site-packages/pdm/backend/wheel.py", line 20, in <module>
    from pdm.backend.base import Builder
  File "/usr/lib/python3.8/site-packages/pdm/backend/base.py", line 12, in <module>
    from pdm.backend.config import Config
  File "/usr/lib/python3.8/site-packages/pdm/backend/config.py", line 9, in <module>
    import tomli_w
ModuleNotFoundError: No module named 'tomli_w'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by frostming** [comment]
The import in that file is indeed: https://github.com/pdm-project/pdm-backend/blob/0ab5642fead716075e527a1fd05a79ebc3105cc9/src/pdm/backend/config.py#L9

I don't know how you specify the build requirments.

**Comment by kloczek** [comment]
> You may need to update the pdm-backend dependency in your global environment

Hmm .. what you mean? 🤔

**Comment by frostming** [comment]
> Hmm .. what you mean? 🤔

There is no problem with the latest code, so it might be your `pdm-backend` is outdated, since you are using `--no-isolation` mode, the old version will be reused, instead of `2.0.6` you thought it is in the title.

**Comment by frostming** [comment]
You can just leave out the `--no-isolation` flag if you don't know what it means.
