### ISSUE TITLE
pdm/backend/editable.py import editables which is not listed as dependencies

### ISSUE THREAD

**Issue by paugier** [pdm-project/pdm-backend#209]
By installing pdm-backend from conda-forge, I managed to get:

```
  Traceback (most recent call last):
    File "/home/users/augier3pi/dev/fluiddyn/.pixi/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/users/augier3pi/dev/fluiddyn/.pixi/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/users/augier3pi/dev/fluiddyn/.pixi/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
      return hook(metadata_directory, config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/users/augier3pi/dev/fluiddyn/.pixi/env/lib/python3.11/site-packages/pdm/backend/__init__.py", line 86, in prepare_metadata_for_build_editable
      from pdm.backend.editable import EditableBuilder
    File "/home/users/augier3pi/dev/fluiddyn/.pixi/env/lib/python3.11/site-packages/pdm/backend/editable.py", line 7, in <module>
      from editables import EditableProject
  ModuleNotFoundError: No module named 'editables'
```

https://pypi.org/project/editables/ is indeed imported in pdm/backend/editable.py but in not listed in https://github.com/pdm-project/pdm-backend/blob/main/pyproject.toml#L26 nor in https://github.com/conda-forge/pdm-backend-feedstock/blob/main/recipe/meta.yaml

**Comment by frostming** [comment]
There might some problem in how you build the wheel, it should read dependencies from `get_requires_for_build_editable` first, and `editables` will be returned by that hook:
https://github.com/pdm-project/pdm-backend/blob/20d0fb1bdd0ce114a160a90cf148b30459740e26/src/pdm/backend/__init__.py#L69-L79

**Comment by frostming** [comment]
So you are performing non-isolated build. And I didn't know pip won't install requires in this case. Maybe you should install `editables` manually.

**Comment by paugier** [comment]
Strange... `editables` is not a build dependency of the project. It's only used indirectly by pdm-backend. Why pdm-backend does not declare it as its own dependency?
