### ISSUE TITLE
package-dir and `FileNotFoundError: [Errno 2] No such file or directory`

### ISSUE THREAD

**Issue by aryadovoy** [pdm-project/pdm-backend#243]
I have **src-layout** and next param in `pyptoject.toml`:
```toml
[tool.pdm.build]
package-dir = "src"
```

It was OK on Python 3.11, but on 3.12 I get error:
```python
Building sdist...
INFO: Inside an active virtualenv /home/aryadovoy/.../app/.venv, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
Built sdist at /home/aryadovoy/.../backend/dist/app-0.1.0.tar.gz
Building wheel from sdist...
See /home/aryadovoy/.local/state/pdm/log/pdm-build-koot3zke.log for detailed debug log.
[BuildError]: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 330, in _get_include_and_exclude_paths
    includes, excludes = self._get_include_and_exclude()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 315, in _get_include_and_exclude
    top_packages = _find_top_packages(build_config.package_dir or ".")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 85, in _find_top_packages
    for path in os.listdir(root):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src'
WARNING: Add '-v' to see the detailed traceback
```

After deleting `package-dir` param it works fine.

<details> <summary>Click to view the log file</summary>

```shelll //
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python==3.12.3
pdm.termui:   Adding requirement pdm-backend
unearth.collector: Collecting links from https://pypi.org/simple/pdm-backend/
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Fetching HTML page https://pypi.org/simple/pdm-backend/
unearth.evaluator: Skipping link <Link https://files.pythonhosted.org/packages/73/52/d4e58bdb2389bfd58c697131ebb5377bcbd29fc2378fc10c0a332d1328c6/pdm_backend-2.0.3.tar.gz (from https://pypi.org/simple/pdm-backend/)>: Yanked due to Incomplete release
pdm.termui:   Adding requirement python==3.12.3
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.3.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.3.0
pdm.termui: Installing pdm-backend@2.3.0...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/e5/89/3f1ff18ebbad5381154b24cff27e25edd8c070be5a9b3d6563bdfc0eec04/pdm_backend-2.3.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/e5/89/3f1ff18ebbad5381154b24cff27e25edd8c070be5a9b3d6563bdfc0eec04/pdm_backend-2.3.0-py3-none-any.whl (from https://pypi.org/simple/pdm-backend/)> (101 kB)
pdm.termui: Synchronization complete.
pdm.termui: /tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/sdist.py:56: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   *self.find_license_files(),
pdm.termui:  - Adding .pdm-build/pyproject.toml -> pyproject.toml
pdm.termui:  - Adding tests/__init__.py -> tests/__init__.py
pdm.termui:  - Adding tests/conftest.py -> tests/conftest.py
pdm.termui:  - Adding tests/test_main.py -> tests/test_main.py
pdm.termui:  - Adding tests/test_migration.py -> tests/test_migration.py
pdm.termui:  - Adding tests/users/test_mutations.py -> tests/users/test_mutations.py
pdm.termui:  - Adding tests/users/test_queries.py -> tests/users/test_queries.py
pdm.termui:  - Adding PKG-INFO -> PKG-INFO
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Reusing shared build env: /tmp/pdm-build-env-0pygzsk_-shared
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
pdm.termui:     json_out["return_val"] = hook(**hook_input["kwargs"])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
pdm.termui:     return _build_backend().build_wheel(
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/__init__.py", line 55, in build_wheel
pdm.termui:     return builder.build(
pdm.termui:            ^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 225, in build
pdm.termui:     files = sorted(self.get_files(context))
pdm.termui:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/wheel.py", line 121, in get_files
pdm.termui:     yield from super().get_files(context)
pdm.termui:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 197, in get_files
pdm.termui:     files = self._collect_files(context)
pdm.termui:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/wheel.py", line 116, in _collect_files
pdm.termui:     (clean_prefix(k), v) for k, v in super()._collect_files(context).items()
pdm.termui:                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 241, in _collect_files
pdm.termui:     includes, excludes = self._get_include_and_exclude_paths()
pdm.termui:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 330, in _get_include_and_exclude_paths
pdm.termui:     includes, excludes = self._get_include_and_exclude()
pdm.termui:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 315, in _get_include_and_exclude
pdm.termui:     top_packages = _find_top_packages(build_config.package_dir or ".")
pdm.termui:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 85, in _find_top_packages
pdm.termui:     for path in os.listdir(root):
pdm.termui:                 ^^^^^^^^^^^^^^^^
pdm.termui: FileNotFoundError: [Errno 2] No such file or directory: 'src'
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/termui.py", line 257, in logging
    yield logger
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/cli/commands/build.py", line 73, in do_build
    whl = WheelBuilder(os.path.join(sdist_out, sdist_name), project.environment).build(dest)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/builders/wheel.py", line 22, in build
    filename = self._hook.build_wheel(out_dir, self.config_settings, metadata_directory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_impl.py", line 256, in build_wheel
    return self._call_hook(
           ^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_impl.py", line 392, in _call_hook
    self._subprocess_runner(
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/builders/base.py", line 259, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/builders/base.py", line 106, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 330, in _get_include_and_exclude_paths
    includes, excludes = self._get_include_and_exclude()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 315, in _get_include_and_exclude
    top_packages = _find_top_packages(build_config.package_dir or ".")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-0pygzsk_-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 85, in _find_top_packages
    for path in os.listdir(root):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src'
```
</details>

**Comment by frostming** [comment]
What's the project structure, do you have `src` folder?

**Comment by aryadovoy** [comment]
@frostming, of course. I have something like this:
```shell
.
├── docs
│   └── …
├── scripts
│   └── …
├── src
│   └── app
└── tests
    └── …
```

**Comment by frostming** [comment]
Start from a clean container and I can't reproduce it:

```
root@6c140b6c3475:/my-project# cat pyproject.toml 
[project]
name = "my-project"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.build]
package-dir = "src"
root@6c140b6c3475:/my-project# pdm build
Building sdist...
Built sdist at /my-project/dist/my_project-0.1.0.tar.gz
Building wheel from sdist...
Built wheel at /my-project/dist/my_project-0.1.0-py3-none-any.whl
root@6c140b6c3475:/my-project#
```

**Comment by aryadovoy** [comment]
@frostming, tried with your `pyproject.toml` — the same problem. But it was OK, when I have PDM 2.15.2 version and Python 3.12.

<details> <summary>Click to view the log file</summary>
```shell
❯ tree
.
├── pyproject.toml
├── README.md
└── src
    └── app

3 directories, 2 files
❯ cat pyproject.toml
[project]
name = "my-project"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.build]
package-dir = "src"

❯ pdm build -v
Building sdist...
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-backend
pdm.termui:   python==3.12.3
pdm.termui:   Adding requirement pdm-backend
pdm.termui:   Adding requirement python==3.12.3
pdm.termui: ======== Starting round 0 ========
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
pdm.termui: Pinning: pdm-backend 2.3.0
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:        python None
pdm.termui:   pdm-backend 2.3.0
pdm.termui: Installing pdm-backend@2.3.0...
pdm.termui: Using cached response for https://files.pythonhosted.org/packages/e5/89/3f1ff18ebbad5381154b24cff27e25edd8c070be5a9b3d6563bdfc0eec04/pdm_backend-2.3.0-py3-none-any.whl
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/e5/89/3f1ff18ebbad5381154b24cff27e25edd8c070be5a9b3d6563bdfc0eec04/pdm_backend-2.3.0-py3-none-any.whl (from https://pypi.org/simple/pdm-backend/)> (101 kB)
pdm.termui: Synchronization complete.
pdm.termui: /tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/sdist.py:56: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
pdm.termui:   *self.find_license_files(),
pdm.termui:  - Adding README.md -> README.md
pdm.termui:  - Adding .pdm-build/pyproject.toml -> pyproject.toml
pdm.termui:  - Adding PKG-INFO -> PKG-INFO
Built sdist at /home/aryadovoy/Documents/code/tmp/pdm/dist/my_project-0.1.0.tar.gz
Building wheel from sdist...
pdm.termui: Preparing environment(Isolated mode) for PEP 517 build...
pdm.termui: Traceback (most recent call last):
pdm.termui:   File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
pdm.termui:     main()
pdm.termui:   File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
pdm.termui:     json_out['return_val'] = hook(**hook_input['kwargs'])
pdm.termui:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
pdm.termui:     return _build_backend().build_wheel(wheel_directory, config_settings,
pdm.termui:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/__init__.py", line 55, in build_wheel
pdm.termui:     return builder.build(
pdm.termui:            ^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 225, in build
pdm.termui:     files = sorted(self.get_files(context))
pdm.termui:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/wheel.py", line 121, in get_files
pdm.termui:     yield from super().get_files(context)
pdm.termui:                ^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 197, in get_files
pdm.termui:     files = self._collect_files(context)
pdm.termui:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/wheel.py", line 116, in _collect_files
pdm.termui:     (clean_prefix(k), v) for k, v in super()._collect_files(context).items()
pdm.termui:                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 241, in _collect_files
pdm.termui:     includes, excludes = self._get_include_and_exclude_paths()
pdm.termui:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 330, in _get_include_and_exclude_paths
pdm.termui:     includes, excludes = self._get_include_and_exclude()
pdm.termui:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 315, in _get_include_and_exclude
pdm.termui:     top_packages = _find_top_packages(build_config.package_dir or ".")
pdm.termui:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pdm.termui:   File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 85, in _find_top_packages
pdm.termui:     for path in os.listdir(root):
pdm.termui:                 ^^^^^^^^^^^^^^^^
pdm.termui: FileNotFoundError: [Errno 2] No such file or directory: 'src'
Traceback (most recent call last):
  File "/home/aryadovoy/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/core.py", line 359, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/core.py", line 277, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/core.py", line 272, in main
    self.handle(project, options)
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/core.py", line 208, in handle
    command.handle(project, options)
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/cli/commands/build.py", line 110, in handle
    self.do_build(
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/cli/commands/build.py", line 73, in do_build
    whl = WheelBuilder(os.path.join(sdist_out, sdist_name), project.environment).build(dest)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/builders/wheel.py", line 22, in build
    filename = self._hook.build_wheel(out_dir, self.config_settings, metadata_directory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/builders/base.py", line 259, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryadovoy/.local/share/pdm/venv/lib64/python3.12/site-packages/pdm/builders/base.py", line 106, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 330, in _get_include_and_exclude_paths
    includes, excludes = self._get_include_and_exclude()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 315, in _get_include_and_exclude
    top_packages = _find_top_packages(build_config.package_dir or ".")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pdm-build-env-qp01f1rh-shared/lib/python3.12/site-packages/pdm/backend/base.py", line 85, in _find_top_packages
    for path in os.listdir(root):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src'
```
</details>

**Comment by frostming** [comment]
Can you make a dockerfile for this?

**Comment by frostming** [comment]
> ```shell
> mkdir src && mkdir src/app
> ```

There is no file included, this is totally invalid usage.

About the error message, it is because the wheel is built from the sdist, and the sdist(which is created sucessfully) doesn't create `src` because there are no files to be included.
